// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Aktivnost
{
    public int AktivnostId { get; set; }

    public string Ime { get; set; }

    public virtual ICollection<Etapa> Etapa { get; set; } = new List<Etapa>();
}