// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Etapa
{
    public int EtapaId { get; set; }

    public string Ime { get; set; }

    public string Opis { get; set; }

    public int PlanProjektaId { get; set; }

    public int AktivnostId { get; set; }

    public virtual Aktivnost Aktivnost { get; set; }

    public virtual PlanProjekta PlanProjekta { get; set; }
}