// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class PlanProjekta
{
    public int PlanProjektaId { get; set; }

    [Display(Name = "Datum planiranog početka: ")]
    public DateTime PlaniraniPočetak { get; set; }

    [Display(Name = "Datum planiranog kraja: ")]
    public DateTime PlaniraniKraj { get; set; }

    [Display(Name = "Datum stvarnog početka: ")]
    public DateTime? StvarniPočetak { get; set; }

    [Display(Name = "Datum stvarnog kraja: ")]
    public DateTime? StvarniKraj { get; set; }

    [Display(Name = "Projekt: ")]
    public int ProjektId { get; set; }

    [Display(Name = "Voditelj: ")]
    public string VoditeljEmail { get; set; }

    public virtual ICollection<Etapa> Etapa { get; set; } = new List<Etapa>();

    public virtual Projekt Projekt { get; set; }

    public virtual Suradnik VoditeljEmailNavigation { get; set; }

    public virtual ICollection<Zahtjev> Zahtjev { get; set; } = new List<Zahtjev>();
}