// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class Posao
{

    public int PosaoId { get; set; }

    public string Opis { get; set; }

    [Display(Name = "Vrijeme početka rada", Prompt = "Unesite mjesto stanovanja")]
    public DateTime VrijemePočetkaRada { get; set; }

    [Display(Name = "Vrijeme kraja rada", Prompt = "Unesite mjesto stanovanja")]
    public DateTime VrijemeKrajaRada { get; set; }

    public int ZadatakId { get; set; }

    [Display(Name = "Vrsta posla", Prompt = "Odaberite vrstu posla")]
    public int VrstaPoslaId { get; set; }

    [Display(Name = "Suradnik", Prompt = "Odaberite suradnika")]
    [Required(ErrorMessage = "Zadatak je obavezno polje!")]
    public string SuradnikEmail { get; set; }

    public virtual Suradnik SuradnikEmailNavigation { get; set; }

    public virtual VrstaPosla VrstaPosla { get; set; }

    public virtual Zadatak Zadatak { get; set; }
}