// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

/// <summary>
/// Razred koji predstavlja model za projektnu karticu
/// </summary>
public partial class ProjektnaKartica
{

    /// <summary>
    /// Jedinstveni identifikator projektna kartica
    /// </summary>
    public int ProjektnaKarticaId { get; set; }

    /// <summary>
    /// Banka u kojoj je otvorena projektna kartica
    /// </summary>
    [Required(ErrorMessage = "Banka je obavezno polje")]
    public string Banka { get; set; }

    /// <summary>
    /// Iban računa projektne kartice
    /// </summary>
    [Required(ErrorMessage = "Iban je obavezno polje")]
    public int Iban { get; set; }

    /// <summary>
    /// Trenutno stanje projektne kartice
    /// </summary>
    [Required(ErrorMessage = "Stanje je obavezno polje")]
    public double Stanje { get; set; }

    /// <summary>
    /// Identifikator projekta kojemu pripada projektna kartica
    /// </summary>
    public int ProjektId { get; set; }

    /// <summary>
    /// Projekt kojemu pripada projektna kartica
    /// </summary>
    public virtual Projekt Projekt { get; set; }

    /// <summary>
    /// Izlazne transakcije sa projektne kartice
    /// </summary>
    public virtual ICollection<Transakcija> TransakcijaProjektnaKarticaIsporučitelj { get; set; } = new List<Transakcija>();

    /// <summary>
    /// Ulazne transakcije na projektnu karticu
    /// </summary>
    public virtual ICollection<Transakcija> TransakcijaProjektnaKarticaPrimatelj { get; set; } = new List<Transakcija>();
}