// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Status
{
    public int StatusId { get; set; }

    public string Ime { get; set; }

    public string ZastavicaAktivnosti { get; set; }

    public virtual ICollection<Zadatak> Zadatak { get; set; } = new List<Zadatak>();
}