// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class Suradnik
{
    public string Email { get; set; }

    [Required(ErrorMessage = "Ime je obavezno polje")]
    public string Ime { get; set; }

    public string Prezime { get; set; }

    [Display(Name = "Mjesto stanovanja", Prompt = "Unesite mjesto stanovanja")]
    public string MjestoStanovanja { get; set; }

    [Display(Name = "Broj telefona", Prompt = "Unesite broj telefona")]
    [Required(ErrorMessage = "Broj telefona je obavezno polje")]
    [RegularExpression(@"^0\d{9}$",
                   ErrorMessage = "Unesite ispravan broj telefona")]
    public string BrojTelefona { get; set; }

    [Display(Prompt = "Unesite URL suradnika")]
    public string URL { get; set; }

    [Display(Name = "Email nadređenog suradnika")]
    public string NadređeniEmail { get; set; }

    public virtual ICollection<Suradnik> InverseNadređeniEmailNavigation { get; set; } = new List<Suradnik>();

    public virtual Suradnik NadređeniEmailNavigation { get; set; }

    public virtual ICollection<PlanProjekta> PlanProjekta { get; set; } = new List<PlanProjekta>();

    public virtual ICollection<Posao> Posao { get; set; } = new List<Posao>();

    public virtual ICollection<Zadatak> Zadatak { get; set; } = new List<Zadatak>();

    public virtual ICollection<Projekt> Projekt { get; set; } = new List<Projekt>();

    public virtual ICollection<Uloga> Uloga { get; set; } = new List<Uloga>();
}