// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Uloga
{
    public int UlogaId { get; set; }

    public string Ime { get; set; }

    public virtual ICollection<Suradnik> SuradnikEmail { get; set; } = new List<Suradnik>();
}