// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

/// <summary>
/// Razred koji predstavlja model za vrstu transakcije
/// </summary>
public partial class VrstaTransakcije
{
    /// <summary>
    /// Jedinstveni identifikator vrste transakcije
    /// </summary>
    public int VrstaTransakcijeId { get; set; }

    /// <summary>
    /// Ime vrste transakcije
    /// </summary>
    public string Ime { get; set; }


    /// <summary>
    /// Sve transakcije ove vrste
    /// </summary>
    public virtual ICollection<Transakcija> Transakcija { get; set; } = new List<Transakcija>();
}