// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VrstaDokumentacije
{
    public int VrstaDokumentacijeId { get; set; }

    public string Ime { get; set; }

    public virtual ICollection<Dokumentacija> Dokumentacija { get; set; } = new List<Dokumentacija>();
}